name: bells_portal
description: A prototype of bells portal system

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

  #sdk: ">=2.16.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.

dependencies:
  firebase_messaging: ^11.2.4
  firebase_core: ^1.10.6
  firebase_analytics: ^9.0.4
  cloud_functions: ^3.2.4
  cloud_firestore: ^1.0.0
  firebase_storage: ^10.2.4
  firebase_auth: ^3.3.4
  firebase_remote_config: ^1.0.0
  get_test: ^3.13.3
  badges: ^2.0.2
  sliding_up_panel: ^2.0.0+1
  shared_preferences: ^2.0.11
  smooth_page_indicator: ^0.2.0
  carousel_slider: ^2.2.1
  mixpanel_flutter: ^1.3.1
  flutter_local_notifications: ^9.2.0
  flutterwave_standard: 1.0.2

  flutter_rating_bar: ^4.0.1

  timeago: ^2.0.27
  jiffy: ^3.0.1
  connectivity: ^3.0.6

  flutter_slidable: ^1.2.0

  flutter_datetime_picker: ^1.5.1
  auto_animated: ^2.1.0
  url_launcher: ^5.5.2
  awesome_dialog: ^1.2.0
  #onesignal_flutter: ^3.2.7
  modal_bottom_sheet:
  flutter_animation_progress_bar: ^2.0.0
  path_provider_android: ^2.0.11

  flutter_paystack: ^1.0.5+1
  permission_handler: ^8.3.0
  cached_network_image: ^3.2.0

  rubber: ^1.0.1
  expandable: ^4.1.4
  flutter_screenutil: ^3.2.0
  smooth_star_rating: ^1.1.1
  material_floating_search_bar: ^0.3.5
  animated_bottom_navigation_bar: ^0.3.2

  algolia: ^1.0.4
  device_preview: ^1.0.0
  quiver: ^2.1.5
  flutter_icons: ^1.1.0
  google_fonts: ^1.1.0
  get: ^3.24.0
  get_it: ^4.0.4
  image_picker: ^0.8.2



  upgrader: ^4.2.1
  agora_rtc_engine: ^4.2.2

  wakelock: ^0.6.0+1

  synchronized: ^3.0.0+2
  flutter_ringtone_player: ^3.2.0






  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/consumer_icon.png"


dependency_overrides:
  visibility_detector: ^0.2.2
  mockito: ^5.0.17
  intl: ^0.17.0
  flutter_svg: ^0.17.4
  http: ^0.13.4
  plugin_platform_interface: ^2.0.2
  xml: ^5.3.1
  #url_launcher: ^5.5.2
  url_launcher: ^6.1.3
  http_parser: ^4.0.0
#  webview_flutter: ^2.0.0


dev_dependencies:


  # network_image_mock: ^1.0.2
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/sounds/
    - assets/lottie_order.json
    - assets/lottie_success.json
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ITCAVANT
      fonts:
        - asset: assets/fonts/ITC_Avant_Garde_Gothic_Bold.otf
          weight: 600
        - asset: assets/fonts/ITC_Avant_Garde_Gothic_Medium.otf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
